name: CI-CD-Pipeline-to-Beastalk

env:
  EB_PACKAGE_S3_BUCKET_NAME : "tf-bucket-for-github-actions"
  EB_APPLICATION_NAME       : "firstapp"
  EB_ENVIRONMENT_NAME       : "envforwebpage"
  DEPLOY_PACKAGE_NAME       : "webpage_${{ github.sha }}.zip"
  AWS_REGION_NAME           : "us-east-1"

on: 
  push:
    branches: 
      - master

jobs:
  my_ci_part:
    runs-on: ubuntu-latest

    steps:
    - name: Git clone our repo
      uses: actions/checkout@v1
       
    - name: Create ZIP package of Webpage
      run : zip -r ${{ env.DEPLOY_PACKAGE_NAME }} ./ -x "*.git*" -x "*.terraform*" -x "*/infrastructure*"
      
